info:
  component: Zuul Server

server:
  port: 8950

zuul:
  ignoredServices: "*"
  routes:
    addresses-service:
      path: /addresses/**
    users-service:
      path: /users/**
    projects-service:
      path: /projects/**
    news-service:
      path: /news/**


security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8850/uaa/user
