info:
  component: Zuul Server

server:
  port: 8765

zuul:
  ignoredServices: "*"
  routes:
    addresses-service:
      path: /addresses/**

zuul:
  ignoredServices: "*"
  routes:
    users-service:
      path: /users/**

zuul:
  ignoredServices: "*"
  routes:
    projects-service:
      path: /projects/**

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
