info:
  component: Zuul Server

server:
  port: 8765

zuul:
  ignoredServices: "*"
  routes:
    addresses-service:
      path: /addresses/**

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

