info:
  component: Zuul Server

server:
  port: 8765

zuul:
  ignoredServices: "*"
  routes:
    addresses-service:
      path: /addresses/**
#    users-service:
#      path: /users/**
#    projects-service:
#      path: /projects/**

#spring:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      userInfoUri: http://localhost:9999/uaa/user
#      clientId: acme
#      clientSecret: acmesecret

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
